const EVENTS = {

    ORDER_CREATED: "ORDER_CREATED",

    ORDER_CANCELLED: "ORDER_CANCELLED",

    ORDER_UPDATED: "ORDER_UPDATED",

    TRADE_EXECUTED: "TRADE_EXECUTED",

    WALLET_UPDATED: "WALLET_UPDATED",

    ORDERBOOK_UPDATED: "ORDERBOOK_UPDATED",

    MARKET_UPDATED: "MARKET_UPDATED"

};

export default EVENTS;