version: "3.9"

services:
  postgres:
    image: postgres:16

    container_name: cryptox-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptox

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

    container_name: cryptox-redis

    restart: always

    ports:
      - "6379:6379"

volumes:
  postgres-data: